### ISSUE TITLE
Working great so far. 👍

### ISSUE THREAD

**Issue by garm0nb0ziaTP** [Qynklee/IDM-Reset-Tool#1]
Using '6.41 build 2' and it seems to be working! Thank you for your time and work. 🙏

**Comment by Qynklee** [comment]
> Using '6.41 build 2' and it seems to be working! Thank you for your time and work. 🙏

Thanks you. Please try a new update v1.2.2 tested on 6.41b2 to fix noise popup mesage in some cases.
