### ISSUE TITLE
Sometimes works.

### ISSUE THREAD

**Issue by garm0nb0ziaTP** [Qynklee/IDM-Reset-Tool#2]
Sometimes the reset tool has to be run again, IDM phones home (I think) and I assume changes it's registry entries? Again, the reset tool still works but not for 30 days. I have been following this for a long time and it seems like the IDM development team keeps moving stuff around, so that a solution is temporary at best. You have to give them credit for the amount of time they put into it.

**Comment by Qynklee** [comment]
I don't really understand what you're saying about what
